version: '3'
services:
  web:
    image: naveed125/nginx-php-fpm:latest
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./src:/var/www/html
    - ./data/nginx/sites-available/:/etc/nginx/sites-available/
    - ./data/root/:/root/
    links:
    - db
    environment:
    - DEPLOYMENT=development

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

    volumes:
    - ./data/mysql:/var/lib/mysql
